#!/usr/bin/env php
<?php

declare(strict_types=1);

use Illuminate\Foundation\Application;
use Illuminate\Contracts\Console\Kernel;

if (! file_exists(__DIR__ . '/vendor/autoload.php')) {
    fwrite(STDERR, "Dependencies missing. Run composer install.\n");
    exit(1);
}

require __DIR__ . '/vendor/autoload.php';

$app = require_once __DIR__ . '/bootstrap/app.php';

$kernel = $app->make(Kernel::class);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    new Symfony\Component\Console\Output\ConsoleOutput
);

$kernel->terminate($input, $status);

exit($status);
